openapi: 3.0.3

info:
  title: Patient Service
  description: Stores patient information
  version: 1.0.0
paths:
  /patients:
    post:
      summary: create a patient in the system
      requestBody:
        $ref: '#/components/requestBodies/PatientCreationDetails'
      responses:
        200:
          $ref: '#/components/responses/PatientCreatedDetails'
        400:
          $ref: '#/components/responses/ValidationError'
        500:
          description: try later or contact us at support@quiquedev.info
components:
  requestBodies:
    PatientCreationDetails:
      description: patient information
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - surname
              - passportNumber
            properties:
              name:
                $ref: '#/components/schemas/Name'
              surname:
                $ref: '#/components/schemas/Surname'
              passportNumber:
                $ref: '#/components/schemas/PassportNumber'
  responses:
    PatientCreatedDetails:
      description: patient information after creation
      content:
        application/json:
          schema:
            type: object
            required:
              - id
              - passportNumber
              - name
              - surname
              - createdAt
            properties:
              id:
                $ref: '#/components/schemas/Id'
              name:
                $ref: '#/components/schemas/Name'
              surname:
                $ref: '#/components/schemas/Surname'
              passportNumber:
                $ref: '#/components/schemas/PassportNumber'
              createdAt:
                $ref: '#/components/schemas/DateTime'
    ValidationError:
      description: patient information is not valid
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                example: body request is not valid
              errors:
                type: array
                items:
                  type: string
                  example: name cannot be blank
  schemas:
    Name:
      type: string
      maxLength: 50
      minLength: 1
      example: Robert
    Surname:
      type: string
      maxLength: 150
      minLength: 1
      example: Mareq
    PassportNumber:
      description: unique for each patient
      type: string
      maxLength: 10
      minLength: 10
      example: 76548353RM
    Id:
      description: internal unique id for each patient
      type: string
      format: uuid
      example: 23e4567-e89b-12d3-a456-426614174000
    DateTime:
      type: string
      format: date-time
      example: 2021-07-21T17:32:28Z
