version: 2
machine: true

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.2

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle test
